<a href="https://colab.research.google.com/github/WilliamKyaww/PyTorch-for-Deep-Learning-Machine-Learning/blob/main/Pytorch_Fundamentalsipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib as plt

import time

print(torch.__version__)

2.6.0+cu124


## **Basics**

In [2]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [4]:
vector.ndim

1

In [5]:
vector.shape

torch.Size([2])

In [6]:
# MATRIX
MATRIX = torch.tensor([[7,8],
                      [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [7]:
MATRIX.ndim

2

In [8]:
MATRIX.shape

torch.Size([2, 2])

In [9]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [10]:
TENSOR.ndim

3

In [11]:
TENSOR.shape

torch.Size([1, 3, 3])

In [12]:
TENSOR2 = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]],
                         [[2,2,2],
                        [2,2,2],
                        [2,2,2]]])
TENSOR2

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]],

        [[2, 2, 2],
         [2, 2, 2],
         [2, 2, 2]]])

In [13]:
TENSOR2.ndim

3

In [14]:
TENSOR2.shape

torch.Size([2, 3, 3])

In [15]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [16]:
TENSOR2[1]

tensor([[2, 2, 2],
        [2, 2, 2],
        [2, 2, 2]])

## **Random Tensors**

In [17]:
random_tensor = torch.rand(3,4)
random_tensor
# This gives us 3 sets of 4 values each

tensor([[0.9258, 0.9279, 0.3889, 0.1389],
        [0.3694, 0.3278, 0.6584, 0.8822],
        [0.3783, 0.8448, 0.1587, 0.1140]])

In [18]:
random_tensor.ndim

2

In [19]:
# Random tensor with similar shape to an image tensor
random_imagine_size_tensor = torch.rand(size=(224,224,3)) #height, #width, #colour
random_imagine_size_tensor.shape, random_imagine_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

## **Zeroes and Ones**


In [20]:
# Tensor of all zeroes with shape 3,4
zeroes = torch.zeros(size=(3,4))
zeroes

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [21]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [22]:
ones.dtype

torch.float32

## **Creating a range of tensors and tensors-like**

In [23]:
one_to_ten = torch.arange(0,10)
one_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
range = torch.arange(start = 0,end = 100, step =5)
range

tensor([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85,
        90, 95])

In [25]:
# Creating tensors where you want to replicate the shape but doeesn't specify it
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## **Tensor Datatype**

**Note**: Tensor datatypes is one of the 3 big error types to run into in Pytorch and Deep Learning

1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device


Data Types:
1. 32-bit takes a bit more memory and therefore more detail but slower
2. 16-bit takes less memory, less detail but faster
There are more datatypes...

Device:
1. Default is cpu
2. Can be cuda (to use Nvidia GPUs)

In [26]:
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                                dtype = None, # what datatype is the tensor
                               device = None, # what device is the tensor on
                               requires_grad = False # whether or not to track gradients with this tensor's operations
                               )
float_32_tensor, float_32_tensor.dtype

(tensor([3., 6., 9.]), torch.float32)

In [27]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [28]:
float_16_tensor = float_32_tensor.type(torch.half)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [29]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [30]:
int_32_tensor = torch.tensor([3,6,9], dtype = torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [31]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Tensor Attributes

1. Tensors not right datatype - to get datatype from a tensor, use "tensor.dtype"
2. Tensors not right shape - to get shape from a tensor, use "tensor.shape"
3. Tensors not on the right device - to get device from a tensor, use "tensor.device"

In [32]:
# Create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.6625, 0.9707, 0.3895, 0.5942],
        [0.9432, 0.3297, 0.4301, 0.4567],
        [0.9189, 0.5424, 0.1502, 0.0325]])

In [33]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.6625, 0.9707, 0.3895, 0.5942],
        [0.9432, 0.3297, 0.4301, 0.4567],
        [0.9189, 0.5424, 0.1502, 0.0325]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating Tensors - Tensor Operations

Tensor operations include:
- Addition
- Subtraction
- Multiplication (element-wise)
- Division
- Matrix Multiplication

In [34]:
# Create a tensor and adds 10 to all values
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [35]:
# Multiplies all values by 10 and prints it (doesn't reassign tensor value)
tensor * 10

tensor([10, 20, 30])

In [36]:
tensor

tensor([1, 2, 3])

In [37]:
# Subtracts all values by 10
tensor - 10

tensor([-9, -8, -7])

In [38]:
# Divides all values by 10
tensor / 10

tensor([0.1000, 0.2000, 0.3000])

In [39]:
# Built in Pytorch function
print(torch.mul(tensor, 10))
print(torch.add(tensor, 10))
print(torch.sub(tensor, 10))
print(torch.div(tensor, 10))

tensor([10, 20, 30])
tensor([11, 12, 13])
tensor([-9, -8, -7])
tensor([0.1000, 0.2000, 0.3000])


## Matrix Multiplication

Two main ways of performing multiplication in neural networks and deep learning:

1. Element-wise Multiplication
2. Matrix Multiplication (dot product)

THere are two main rules that performing matrix multiplication needs to satisfy:
1. The **inner dimenstions** must match:
* `(3, 2) @ (3,2)` won't work
* `(2,3) @ (3,2)` will work
* `(3,2) @ (2,3)` will work

2. The resulting matric has the shape of the **outer dimensions**:
* `(2,3) @ (3,2)` -> `(2,2)`
* `(3,2) @ (2,3)` -> `(3,3)`

Note: @ refers to matrix multiplication (dot product)

In [40]:
# Won't work - intended
torch.matmul(torch.rand(3,2), torch.rand(3,2))

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [41]:
# Will work
torch.matmul(torch.rand(3,2), torch.rand(2,3))

tensor([[0.1971, 1.2148, 0.6636],
        [0.1835, 1.0812, 0.5973],
        [0.2348, 1.3460, 0.7488]])

In [42]:
# Will work
torch.matmul(torch.rand(2,3), torch.rand(3,2))

tensor([[0.4398, 0.4949],
        [0.4342, 0.6810]])

In [43]:
# Element wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [44]:
# Matrix multiplication - Dot Product using built-in fuction (1+4+9)
torch.matmul(tensor, tensor)

tensor(14)

In [45]:
tensor

tensor([1, 2, 3])

In [46]:
# Matrix multiplication by hand
1*1 + 2*2 + 3*3

14

In [47]:
tensor @ tensor

tensor(14)

In [48]:
tensor

tensor([1, 2, 3])

In [49]:
## Won't work - unintended (not sure why)
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
value

TypeError: 'Tensor' object is not callable

In [50]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 111 µs, sys: 16 µs, total: 127 µs
Wall time: 132 µs


tensor(14)

## One of the most common errors in deep learning is shape errors

In [51]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1,2],
                        [3,4],
                        [5,6]])

tensor_B = torch.tensor([[7,10],
                        [8,11],
                        [9,12]])

tensor_A.shape, tensor_B.shape


(torch.Size([3, 2]), torch.Size([3, 2]))

In [52]:
# Won't work
torch.mm(tensor_A, tensor_B) # torch.mm same as torch.matmul

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

We cannot multiply these two tensors because they have the same shape.

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**

A **transpose** switches the axes or dimensions of a given tensor

In [53]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [54]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [55]:
# The matrix multiplication operation works when tensor_B is transposed

print(f"Original shapes: \n tensor_A = {tensor_A.shape}, \n tensor_B = {tensor_B.shape}")
print(f"\nNew shapes: \n tensor_A = {tensor_A.shape}, \n tensor_B = {tensor_B.T.shape}")

print(f"\nMultiplying: {tensor_A.shape} @ {tensor_B.T.shape} - inner dimensions must match")
print(f"\nOutput:\n {torch.matmul(tensor_A, tensor_B.T)}")

print(f"\nOutput shape: {torch.matmul(tensor_A, tensor_B.T).shape}")


Original shapes: 
 tensor_A = torch.Size([3, 2]), 
 tensor_B = torch.Size([3, 2])

New shapes: 
 tensor_A = torch.Size([3, 2]), 
 tensor_B = torch.Size([2, 3])

Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) - inner dimensions must match

Output:
 tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


## Finding the min, max, mean, sum etc (tensor aggregation)

In [56]:
# Create a tensor
x = torch.arange(0, 100, 10)

In [57]:
# Find the min
torch.min(x), x.min() # both syntax works

(tensor(0), tensor(0))

In [58]:
# Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [59]:
# Find the mean - won't work (intended)
torch.mean(x), x.mean()

# This doesn't work as it not the correct datatype

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [60]:
# The datatype of the tensor
x.dtype

# int64 is "Long"
# the "mean" function can't work on tensors with dataype Long

torch.int64

In [61]:
# The torch.mean() function requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [62]:
# Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

## Finding the positional min and max

In [63]:
x = torch.arange(1, 100, 10)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [64]:
# Find the position in tensor that has the minimum value with argmin() - returns index position of target tensor where minimum value occurs
x.argmin()

tensor(0)

In [65]:
x[0]

tensor(1)

In [66]:
# Find the position in tensor that has the maximum value with argmax()
x.argmax()

tensor(9)

In [67]:
x[9]

tensor(91)

## Reshaping, viewing, stacking, squeezing, unsqueezing, permuting tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - return a view of an input tensor of certain shape, but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack - vertical stack) or side by side (hstack - horizontal stack)
* Squeezing - removes all `1` dimensions from a tensor
* Unsqueezing - adds a `1` dimentsions to a target tensor
* Permuting - return a view of the input with dimensions permuted (swapped) in a certian way

In [68]:
# Create a tensor
import torch

x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [69]:
# Add an extra dimension
x_reshaped = x.reshape(1,7)
x_reshaped, x_reshaped.shape

# Here we are trying to squeeze 9 elements into a tensor of shape 7

RuntimeError: shape '[1, 7]' is invalid for input of size 9

In [ ]:
# Timestamp - 3:04:30